!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO: []
mEncoders: []
mGyros: []
mPwm:
- mHandle: 101
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CAN SC 1
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 103
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CAN SC 3
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 104
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CAN SC 4
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 106
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: CAN SC 6
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
mRelays: []
mSimulatorComponents: []
mSolenoids: []
